settings:
  title: 'guoxiaodi'
  url: 'https://status-page.igxiaodi.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: apiguoxiaodi # unique identifier
    name: api.guoxiaodi.com
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://api.iguoxiaodi.com/api/no-auth/getTimeLongOfNow' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-guoxiaodi-com
    name: www.iguoxiaodi.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.iguoxiaodi.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: open-api-com
    name: openapi.guoxiaodi.com
    url: 'https://openapi.iguoxiaodi.com/'
    method: GET
    expectStatus: 404
